# Different sources put the same places in different regions (e.g. SGDP
# puts Mozabite into Africa, while HGDP puts it into Middle East).  This
# dictionary somewhat arbitrarily puts all sources into consistent
# (but somewhat arbitrary) regions.
regions = {
    ('SGDP', 'Abkhasian'): 'Europe',
    ('SGDP', 'Adygei'): 'Europe',
    ('SGDP', 'Albanian'): 'Europe',
    ('SGDP', 'Aleut'): 'Central Asia',
    ('SGDP', 'Altaian'): 'Central Asia',
    ('SGDP', 'Ami'): 'East Asia',
    ('SGDP', 'Armenian'): 'Europe',
    ('SGDP', 'Atayal'): 'East Asia',
    ('SGDP', 'Australian'): 'Oceania',
    ('SGDP', 'Balochi'): 'South Asia',
    ('SGDP', 'BantuHerero'): 'Africa',
    ('SGDP', 'BantuKenya'): 'Africa',
    ('SGDP', 'BantuTswana'): 'Africa',
    ('SGDP', 'Basque'): 'Europe',
    ('SGDP', 'BedouinB'): 'Middle East',
    ('SGDP', 'Bengali'): 'South Asia',
    ('SGDP', 'Bergamo'): 'Europe',
    ('SGDP', 'Biaka'): 'Africa',
    ('SGDP', 'Bougainville'): 'Oceania',
    ('SGDP', 'Brahmin'): 'South Asia',
    ('SGDP', 'Brahui'): 'South Asia',
    ('SGDP', 'Bulgarian'): 'Europe',
    ('SGDP', 'Burmese'): 'East Asia',
    ('SGDP', 'Burusho'): 'South Asia',
    ('SGDP', 'Cambodian'): 'East Asia',
    ('SGDP', 'Chane'): 'America',
    ('SGDP', 'Chechen'): 'Europe',
    ('SGDP', 'Chukchi'): 'Central Asia',
    ('SGDP', 'Crete'): 'Europe',
    ('SGDP', 'Czech'): 'Europe',
    ('SGDP', 'Dai'): 'East Asia',
    ('SGDP', 'Daur'): 'East Asia',
    ('SGDP', 'Dinka'): 'Africa',
    ('SGDP', 'Druze'): 'Middle East',
    ('SGDP', 'Dusun'): 'Oceania',
    ('SGDP', 'English'): 'Europe',
    ('SGDP', 'Esan'): 'Africa',
    ('SGDP', 'Eskimo_Chaplin'): 'Central Asia',
    ('SGDP', 'Eskimo_Naukan'): 'Central Asia',
    ('SGDP', 'Eskimo_Sireniki'): 'Central Asia',
    ('SGDP', 'Estonian'): 'Europe',
    ('SGDP', 'Even'): 'Central Asia',
    ('SGDP', 'Finnish'): 'Europe',
    ('SGDP', 'French'): 'Europe',
    ('SGDP', 'Gambian'): 'Africa',
    ('SGDP', 'Georgian'): 'Europe',
    ('SGDP', 'Greek'): 'Europe',
    ('SGDP', 'Han'): 'East Asia',
    ('SGDP', 'Hawaiian'): 'Oceania',
    ('SGDP', 'Hazara'): 'South Asia',
    ('SGDP', 'Hezhen'): 'East Asia',
    ('SGDP', 'Hungarian'): 'Europe',
    ('SGDP', 'Icelandic'): 'Europe',
    ('SGDP', 'Igorot'): 'Oceania',
    ('SGDP', 'Iranian'): 'Middle East',
    ('SGDP', 'Iraqi_Jew'): 'Middle East',
    ('SGDP', 'Irula'): 'South Asia',
    ('SGDP', 'Itelman'): 'Central Asia',
    ('SGDP', 'Japanese'): 'East Asia',
    ('SGDP', 'Jordanian'): 'Middle East',
    ('SGDP', 'Ju_hoan_North'): 'Africa',
    ('SGDP', 'Kalash'): 'South Asia',
    ('SGDP', 'Kapu'): 'South Asia',
    ('SGDP', 'Karitiana'): 'America',
    ('SGDP', 'Khomani_San'): 'Africa',
    ('SGDP', 'Khonda_Dora'): 'South Asia',
    ('SGDP', 'Kinh'): 'East Asia',
    ('SGDP', 'Korean'): 'East Asia',
    ('SGDP', 'Kusunda'): 'South Asia',
    ('SGDP', 'Kyrgyz'): 'Central Asia',
    ('SGDP', 'Lahu'): 'East Asia',
    ('SGDP', 'Lezgin'): 'Europe',
    ('SGDP', 'Luhya'): 'Africa',
    ('SGDP', 'Luo'): 'Africa',
    ('SGDP', 'Madiga'): 'South Asia',
    ('SGDP', 'Makrani'): 'South Asia',
    ('SGDP', 'Mala'): 'South Asia',
    ('SGDP', 'Mandenka'): 'Africa',
    ('SGDP', 'Mansi'): 'Central Asia',
    ('SGDP', 'Maori'): 'Oceania',
    ('SGDP', 'Masai'): 'Africa',
    ('SGDP', 'Mayan'): 'America',
    ('SGDP', 'Mbuti'): 'Africa',
    ('SGDP', 'Mende'): 'Africa',
    ('SGDP', 'Miao'): 'East Asia',
    ('SGDP', 'Mixe'): 'America',
    ('SGDP', 'Mixtec'): 'America',
    ('SGDP', 'Mongola'): 'Central Asia',
    ('SGDP', 'Mozabite'): 'Middle East',
    ('SGDP', 'Naxi'): 'East Asia',
    ('SGDP', 'North_Ossetian'): 'Europe',
    ('SGDP', 'Norwegian'): 'Europe',
    ('SGDP', 'Orcadian'): 'Europe',
    ('SGDP', 'Oroqen'): 'East Asia',
    ('SGDP', 'Palestinian'): 'Middle East',
    ('SGDP', 'Papuan'): 'Oceania',
    ('SGDP', 'Pathan'): 'South Asia',
    ('SGDP', 'Piapoco'): 'America',
    ('SGDP', 'Pima'): 'America',
    ('SGDP', 'Polish'): 'Europe',
    ('SGDP', 'Punjabi'): 'South Asia',
    ('SGDP', 'Quechua'): 'America',
    ('SGDP', 'Relli'): 'South Asia',
    ('SGDP', 'Russian'): 'Europe',
    ('SGDP', 'Saami'): 'Europe',
    ('SGDP', 'Saharawi'): 'Middle East',
    ('SGDP', 'Samaritan'): 'Middle East',
    ('SGDP', 'Sardinian'): 'Europe',
    ('SGDP', 'She'): 'East Asia',
    ('SGDP', 'Sindhi'): 'South Asia',
    ('SGDP', 'Somali'): 'Africa',
    ('SGDP', 'Spanish'): 'Europe',
    ('SGDP', 'Surui'): 'America',
    ('SGDP', 'Tajik'): 'Central Asia',
    ('SGDP', 'Thai'): 'East Asia',
    ('SGDP', 'Tlingit'): 'Central Asia',
    ('SGDP', 'Tu'): 'East Asia',
    ('SGDP', 'Tubalar'): 'Central Asia',
    ('SGDP', 'Tujia'): 'East Asia',
    ('SGDP', 'Turkish'): 'Middle East',
    ('SGDP', 'Tuscan'): 'Europe',
    ('SGDP', 'Ulchi'): 'Central Asia',
    ('SGDP', 'Uygur'): 'Central Asia',
    ('SGDP', 'Xibo'): 'East Asia',
    ('SGDP', 'Yadava'): 'South Asia',
    ('SGDP', 'Yakut'): 'Central Asia',
    ('SGDP', 'Yemenite_Jew'): 'Middle East',
    ('SGDP', 'Yi'): 'East Asia',
    ('SGDP', 'Yoruba'): 'Africa',
    ('SGDP', 'Zapotec'): 'America',
    ('HGDP', 'Adygei'): 'Europe',
    ('HGDP', 'Balochi'): 'South Asia',
    ('HGDP', 'BantuKenya'): 'Africa',
    ('HGDP', 'BantuSouthAfrica'): 'Africa',
    ('HGDP', 'Basque'): 'Europe',
    ('HGDP', 'Bedouin'): 'Middle East',
    ('HGDP', 'BergamoItalian'): 'Europe',
    ('HGDP', 'Biaka'): 'Africa',
    ('HGDP', 'Bougainville'): 'Oceania',
    ('HGDP', 'Brahui'): 'South Asia',
    ('HGDP', 'Burusho'): 'South Asia',
    ('HGDP', 'Cambodian'): 'East Asia',
    ('HGDP', 'Colombian'): 'America',
    ('HGDP', 'Dai'): 'East Asia',
    ('HGDP', 'Daur'): 'East Asia',
    ('HGDP', 'Druze'): 'Middle East',
    ('HGDP', 'French'): 'Europe',
    ('HGDP', 'Han'): 'East Asia',
    ('HGDP', 'Hazara'): 'South Asia',
    ('HGDP', 'Hezhen'): 'East Asia',
    ('HGDP', 'Japanese'): 'East Asia',
    ('HGDP', 'Kalash'): 'South Asia',
    ('HGDP', 'Karitiana'): 'America',
    ('HGDP', 'Lahu'): 'East Asia',
    ('HGDP', 'Makrani'): 'South Asia',
    ('HGDP', 'Mandenka'): 'Africa',
    ('HGDP', 'Maya'): 'America',
    ('HGDP', 'Mbuti'): 'Africa',
    ('HGDP', 'Miao'): 'East Asia',
    ('HGDP', 'Mongolian'): 'Central Asia',
    ('HGDP', 'Mozabite'): 'Middle East',
    ('HGDP', 'Naxi'): 'East Asia',
    ('HGDP', 'NorthernHan'): 'East Asia',
    ('HGDP', 'Orcadian'): 'Europe',
    ('HGDP', 'Oroqen'): 'East Asia',
    ('HGDP', 'Palestinian'): 'Middle East',
    ('HGDP', 'PapuanHighlands'): 'Oceania',
    ('HGDP', 'PapuanSepik'): 'Oceania',
    ('HGDP', 'Pathan'): 'South Asia',
    ('HGDP', 'Pima'): 'America',
    ('HGDP', 'Russian'): 'Europe',
    ('HGDP', 'San'): 'Africa',
    ('HGDP', 'Sardinian'): 'Europe',
    ('HGDP', 'She'): 'East Asia',
    ('HGDP', 'Sindhi'): 'South Asia',
    ('HGDP', 'Surui'): 'America',
    ('HGDP', 'Tu'): 'East Asia',
    ('HGDP', 'Tujia'): 'East Asia',
    ('HGDP', 'Tuscan'): 'Europe',
    ('HGDP', 'Uygur'): 'Central Asia',
    ('HGDP', 'Xibo'): 'East Asia',
    ('HGDP', 'Yakut'): 'Central Asia',
    ('HGDP', 'Yi'): 'East Asia',
    ('HGDP', 'Yoruba'): 'Africa',
    ('TGP', 'ASW'): 'Africa',
    ('TGP', 'ACB'): 'Africa',
    ('TGP', 'BEB'): 'South Asia',
    ('TGP', 'GBR'): 'Europe',
    ('TGP', 'CLM'): 'America',
    ('TGP', 'CDX'): 'East Asia',
    ('TGP', 'ESN'): 'Africa',
    ('TGP', 'FIN'): 'Europe',
    ('TGP', 'GWD'): 'Africa',
    ('TGP', 'GIH'): 'South Asia',
    ('TGP', 'CHB'): 'East Asia',
    ('TGP', 'IBS'): 'Europe',
    ('TGP', 'JPT'): 'East Asia',
    ('TGP', 'KHV'): 'East Asia',
    ('TGP', 'LWK'): 'Africa',
    ('TGP', 'MSL'): 'Africa',
    ('TGP', 'MXL'): 'America',
    ('TGP', 'PEL'): 'America',
    ('TGP', 'PUR'): 'America',
    ('TGP', 'PJL'): 'South Asia',
    ('TGP', 'CHS'): 'East Asia',
    ('TGP', 'STU'): 'South Asia',
    ('TGP', 'ITU'): 'South Asia',
    ('TGP', 'TSI'): 'Europe',
    ('TGP', 'CEU'): 'Europe',
    ('TGP', 'YRI'): 'Africa',
}
